/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        "surface-container": "#eceef0",
        "on-primary": "#ffffff",
        "on-background": "#191c1e",
        "on-secondary-fixed-variant": "#364b41",
        "inverse-on-surface": "#eff1f3",
        "primary": "#05162b",
        "on-surface-variant": "#44474d",
        "surface-bright": "#f7f9fb",
        "secondary-fixed": "#d0e8db",
        "secondary-container": "#cde5d8",
        "surface-container-high": "#e6e8ea",
        "on-tertiary-fixed": "#002204",
        "on-secondary-container": "#51675d",
        "surface-variant": "#e0e3e5",
        "on-secondary-fixed": "#0a1f17",
        "background": "#f7f9fb",
        "on-primary-fixed-variant": "#38485f",
        "inverse-primary": "#b7c7e4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "outline-variant": "#c4c6cd",
        "primary-fixed": "#d4e3ff",
        "tertiary-container": "#003308",
        "surface-container-highest": "#e0e3e5",
        "error": "#ba1a1a",
        "outline": "#75777d",
        "on-surface": "#191c1e",
        "tertiary": "#001c03",
        "primary-fixed-dim": "#b7c7e4",
        "surface-tint": "#505f78",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "primary-container": "#1b2b41",
        "surface-dim": "#d8dadc",
        "on-error-container": "#93000a",
        "on-primary-container": "#8292ad",
        "tertiary-fixed-dim": "#82db7e",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#0b1c31",
        "tertiary-fixed": "#9df898",
        "inverse-surface": "#2d3133",
        "error-container": "#ffdad6",
        "surface": "#f7f9fb",
        "on-tertiary-fixed-variant": "#005312",
        "secondary": "#4d6359",
        "on-tertiary-container": "#4ea44f",
        "secondary-fixed-dim": "#b4ccbf",
        brand: '#10b981',
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1.5rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"],
        "inter": ["Inter", "sans-serif"],
        sans: ['Inter', 'sans-serif'],
        heading: ['Outfit', 'sans-serif'],
      }
    },
  },
  plugins: [],
};
